# https://gist.github.com/palewire/12c4b2b974ef735d22da7493cf7f4d37

# builds and pushes docker image to the gcp container registry.
# tags image with the SHA of commit so that the tag change can be picked up by terraform
name: Release
on:
    push:
        # branches:
        #     - main
        #     - github-action

jobs:
    docker-release:
        name: Tagged Docker release to Google Artifact Registry
        runs-on: ubuntu-latest
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        # <-- Notice that I'm filtering here to only run when a tagged commit is pushed
        # git commit -am 'commit message'
        # git tag -a v1.0.0 -m 'release docker image initial'
        # git push --tags

        permissions:
            contents: 'read'
            id-token: 'write'

        steps:
            - id: checkout
              name: Checkout
              uses: actions/checkout@v2

            - id: auth
              name: Authenticate with Google Cloud
              uses: google-github-actions/auth@v0
              with:
                  token_format: access_token
                  workload_identity_provider: ${{ vars.GCP_PROVIDER_ID }}
                  service_account: ${{ vars.GCP_SERVICE_ACCOUNT_EMAIL }}
                  access_token_lifetime: 300s

            - name: Login to Artifact Registry
              uses: docker/login-action@v1
              with:
                  registry: ${{ vars.GCP_REGION }}-docker.pkg.dev
                  username: oauth2accesstoken
                  password: ${{ steps.auth.outputs.access_token }}

            - name: Setup Environment (PR)
              if: ${{ github.event_name == 'pull_request' }}
              shell: bash
              run: |
                  echo "LAST_COMMIT_SHA=${{ github.event.pull_request.head.sha }}" >> ${GITHUB_ENV}

            - name: Setup Environment (Push)
              if: ${{ github.event_name == 'push' }}
              shell: bash
              run: |
                  echo "LAST_COMMIT_SHA=${GITHUB_SHA}" >> ${GITHUB_ENV}

            - name: print build tag
              run: |
                  echo "BUILD_TAG=${LAST_COMMIT_SHA:0:7}" >> $GITHUB_ENV

            #### Set the Docker image URL as a variable  <added july 1>
            - id: set-image-url
              name: Set image URL variable
              run: echo "::set-output name=image-url::${{ vars.GCP_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/cloud-run-source-deploy/shop-backend-stripe-mongo-gh-actions:${{ env.BUILD_TAG }}"
            #####
            - id: docker-push-tagged
              name: Tag Docker image and push to Google Artifact Registry
              uses: docker/build-push-action@v2
              with:
                  push: true
                  tags: |
                      ${{ steps.set-image-url.outputs.image-url }}

              # tags: ${{ vars.GCP_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/cloud-run-source-deploy/shop-backend-stripe-mongo-gh-actions:${{ env.BUILD_TAG }}

            - name: Print Docker tags
              run: |
                  echo "Docker tag:"
                  echo "${{ steps.set-image-url.outputs.image-url }}"

              # echo "${{ vars.GCP_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/cloud-run-source-deploy/shop-backend-stripe-mongo-gh-actions:${{ env.BUILD_TAG }}"

# TFC via github actions
# https://developer.hashicorp.com/terraform/tutorials/automation/github-actions
# need terraform to get the variable of image from the tag output
